### PR TITLE
De-globalization

### PR DESCRIPTION
**Pull request by Road-block**
image

Little proof I didn't cause regressions (break existing functionality)

Ok the discussion bit 😄 

Anything that is not defined as local is put in a global addon memory space in WoW Addons.
That makes it easy to break other addons (or the base UI) with name collisions.
It also exposes your addon to the same from other addons.

It is good practice to keep all the things that don't specifically need to be global self-contained (for example a globally accessible frame name is needed for using the `UISpecialFrames` array)

The same applies for saved variable arrays, they are also in the global namespace. In their case it cannot be avoided so a good practice is to make the saved variables array name unique.

Since you cannot have 2 addons named the same in your AddOns folder any combination of `YourAddonName`postfix is good.
`TransmogOutfitManagerDB` for example.

To help addon authors pass around variables and methods within their addon with no need to have everything in a monolithic .lua file they provide a special vararg that the WoW client passes into every .lua file loaded from the addon's .toc 

`local addonName, addon = ... ` at the top of any Lua file loaded by your .toc will get passed your addon name as a string and an array that is accessible by any other file in your addon but is __not__ put in the global namespace (that all addons share)

So it is essentially an "addon scope".

In this pull request I have used that to "tuck" all the unnecessary global functions neatly into your addon object `MOP`.

If you want something to be accessible globally you can still export it to the global environment but in a controlled way with a single (or few) access points.

For example `_G[addonName] = MOP` at the bottom of TOM_Util.lua would make everything tucked under MOP accessible from the outside under `TransmogOutfitManager`

### CODE REVIEW

**Comment by verkkila** [comment]
First of all, thank you for taking the time to go through the code and write all this up. Not to mention the refactoring.

I pulled this PR/branch locally and I'm going over the code atm, I will try to merge it asap.
There are a couple of regressions (missing SetBackdrop param for row 1 column 1 model, dropdown not opening). The first one I have a commit for and the second I'm looking at now.

With the change to the SavedVariables name I will assume that once the new version is published any outfits saved with the old version will be lost. Does the WoW Addon ecosystem preserve "deprecated" SavedVariables so that users can manually change the name from 'MyOutfits' -> 'TransmogOutfitManagerDB' by editing the file for example?

In general I agree with the spirit of the changes 100% and I don't intend on polluting the global namespace.

**Comment by Road-block** [comment]
That is correct about the saved variables.
You could do probably do some juggling with CopyTable to move stuff over but it's early enough in the addon's life that a one time remake of outfits won't be a terrible inconvenience I don't think. 

This is going to be a popular addon.

PS. Sorry about the regressions.

**Comment by verkkila** [comment]
No need to apologize, you've saved me a lot of tech debt.

I've informed the users to back-up their SavedVariables, and I'll put instructions to recover the old outfits on the next release.

**Comment by Road-block** [comment]
Oh I see what I did with the backdrop, I cut the anonymous table out from the first SetBackdrop and didn't replace it with the reference 😵‍💫

**Comment by verkkila** [comment]
I'm just gonna merge this branch now to make working with Git & GitHub easier.

**Pull request merged**
